EMP-310: Complex page style formatting
ministryofjustice/laa-crime-equinity-historical-data-frontend pull request #147
Opened 2024-05-30 15:08 UTC by muyinatech

**Changes made:**
- Added date-fns library for date & time formatting
- Added FieldType type
- Added type property to ConfigField type
- Updated CRM5 display config to specify currency, date, time formatting for the required fields
- Moved display config validation to a separate file
- Added additional display config validation tests
- Created CRM Display Field formatter for format fields for the given type

2024-05-30 15:29 UTC, muyinatech commented on server/services/config/crm5DisplayConfig.json
> +              "apiField": "AllCosts.AccruedCosts.Attendance.time",
Same explanation as below

2024-05-31 13:18 UTC, sarahyjja commented on server/utils/crmFieldFormatter.test.ts
> +      expect(result).toEqual('14 02 2024')
The date format should not retrieve the `0` in day and month
For eg.: 14 2 2024

2024-05-31 13:25 UTC, sarahyjja commented on server/utils/crmFieldFormatter.ts
> +  return format(date, 'dd MM yyyy')
Docs about not retrieving the `0` : https://date-fns.org/v3.6.0/docs/intlFormat

2024-05-31 13:27 UTC, sarahyjja requested changes
Just a minor change about not retrieving the `0` in `date` format (posted a link to the intlFormat). 
Out of that it LGTM!

2024-05-31 14:06 UTC, sarahyjja approved these changes
LGTM

2024-05-31 14:11 UTC, merged